const DEFAULT_MIN = 0;
const DEFAULT_MAX = 100;
const DEFAULT_STEP = 1;
const DEFAULT_VALUE = 0;
const DEFAULT_VALUE_2 = null;
const DEFAULT_GRID_DENSITY = 1;
const DEFAULT_RANGE = false;
const DEFAULT_VERTICAL = false;
const DEFAULT_SHOW_BUBBLE = false;
const DEFAULT_SHOW_GRID = false;
const DEFAULT_SHOW_BAR = false;

const GRID_DENSITY_MIN = 1;
const GRID_DENSITY_MAX = 100;

export {
  DEFAULT_MIN,
  DEFAULT_MAX,
  DEFAULT_STEP,
  DEFAULT_VALUE,
  DEFAULT_VALUE_2,
  DEFAULT_GRID_DENSITY,
  DEFAULT_RANGE,
  DEFAULT_VERTICAL,
  DEFAULT_SHOW_BUBBLE,
  DEFAULT_SHOW_GRID,
  DEFAULT_SHOW_BAR,
  GRID_DENSITY_MIN,
  GRID_DENSITY_MAX,
};
